# This is a basic workflow to help you get started with Actions

name: Deploy to Env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:

env:
  RG_Name: RG11

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
     RG_Name: ${{env.RG_Name}}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to azure
        with: 
          creds: ${{secrets.AZ_DEV_CRED}}
      - uses: azure/cli@v1
        name: Create resource group
        with:
          inlineScript: az group create --location WestEurope --name ${{env.RG_Name}}

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    environment: prd
    env:
     RG_Name: ${{env.RG_Name}}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: Sign in to azure
        with: 
          creds: ${{secrets.AZ_PRD_CRED}}
      - uses: azure/cli@v1
        name: Create resource group
        with:
          inlineScript: az group create --location WestEurope --name ${{env.RG_Name}}
